service: flettsgetmarried-api
frameworkVersion: '>=2.25.2 < 3.0.0'

provider:
  name: aws
  runtime: go1.x
  region: ap-southeast-2
  stage: ${opt:staging, 'prod'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:ap-southeast-2:292374005836:table/flettsgetmarried"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  rsvp:
    handler: bin/rsvp
    name: ${self:service}-rsvp-${self:provider.stage}
    description: "Creates an RSVP update"
    memorySize: 128
    timeout: 10

  search:
    handler: bin/search
    name: ${self:service}-search-${self:provider.stage}
    description: "Search for attendees and get their invites"

resources:
  Resources:
    rsvpTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: flettsgetmarried
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
