name: Build and publish flettsgetmarried.com
# on:
#   release:
#     types: [published]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: npm install nuxt
        working-directory: website
      - run: npm ci
        working-directory: website
      - run: npm run build
        working-directory: website
      - run: npm run generate
        working-directory: website
      - name: Upload static web files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: website/dist/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-2
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: python -m pip install awscli
      - name: Download static web files
        uses: actions/download-artifact@v2
        with:
          name: dist
      - run: aws s3 sync --delete --sse AES256 . s3://flettsgetmarried.com
